quickstartup/qs_accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "qs_accounts"

urlpatterns = [
    # Auth
    path("signin/", views.LoginView.as_view(), name="signin"),
    path("signout/", views.LogoutView.as_view(), name="signout"),

    # Password reset
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<reset_token>/", views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),

    # Basic Registration
    path("signup/", view=views.SignupView.as_view(), name="signup"),
    path('signup/complete/', view=TemplateView.as_view(template_name='accounts/signup-complete.html', ),
         name='signup_complete'),
    path('activate/<activation_key>/', view=views.SignupActivationView.as_view(), name='activate'),
    path('signup/closed/', TemplateView.as_view(template_name='accounts/signup-closed.html'),
         name='signup_closed'),

    # Profile
    path("profile/", view=views.UserProfileView.as_view(), name="profile"),
    path("profile/password/", views.PasswordChangeView.as_view(), name="password_change"),
    path("profile/email/", views.EmailChangeView.as_view(), name="email_change"),
    path("profile/email/<activation_key>/", views.EmailChangeConfirmationView.as_view(),
         name="email_change_confirmation"),
]

quickstartup/qs_contacts/urls.py
from django.urls import path

from . import views

app_name = "qs_contacts"

urlpatterns = [
    path("", views.ContactView.as_view(), name="contact"),
]

testproject/urls.py
from django.urls import include, path

urlpatterns = [
    path("app/", include("testproject.testapp.urls")),
    path("", include("quickstartup.urls")),
]

quickstartup/qs_accounts/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import (AbstractBaseUser as DjangoAbstractBaseUser,
                                           BaseUserManager as DjangoBaseUserManager)

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import PermissionsMixin

class BaseUserManager(DjangoBaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        email = self.normalize_email(email)

        user_model = get_user_model()
        user = user_model(email=email, is_active=True, is_staff=is_staff, is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email=None, password=None, is_staff=False, **extra_fields):
        return self._create_user(email, password, is_staff, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)

    def activate(self, username):
        user = self.get_by_natural_key(username)
        user.is_active = True
        user.save()
        return user

    def confirm_new_email(self, username):
        user = self.get_by_natural_key(username)
        user.confirm_new_email()
        return user


# noinspection PyAbstractClass
class AbstractBaseUser(DjangoAbstractBaseUser,PermissionsMixin):
    objects = BaseUserManager()

    email = models.EmailField(_("e-mail"), max_length=255, unique=True, db_index=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    is_active = models.BooleanField(_("active"), default=False)
    is_staff = models.BooleanField(_("staff"), default=False)
    is_superuser = models.BooleanField(_('superuser'), default=False)

    new_email = models.EmailField(_("new e-mail"), max_length=255, null=True, blank=True, db_index=True)

    USERNAME_FIELD = "email"

    class Meta(DjangoAbstractBaseUser.Meta):
        abstract = True

    def get_short_name(self):
        return self.email

    def confirm_new_email(self):
        if not self.new_email:
            return

        self.email = self.new_email
        self.new_email = None
        self.save()


class AbstractUser(AbstractBaseUser):
    name = models.CharField(max_length=255, blank=True, null=True)

    class Meta(AbstractBaseUser.Meta):
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True

    def get_full_name(self):
        return self.name


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

quickstartup/qs_accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_backends, get_user_model, login as user_login, views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.signing import BadSignature, SignatureExpired, Signer, TimestampSigner
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.module_loading import import_string
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView, TemplateView, UpdateView

from quickstartup.settings_utils import get_configuration, get_object_from_configuration
from .signals import user_activated
from .forms import AuthenticationForm


# noinspection PyUnresolvedReferences
class ProfileMixin(object):
    # noinspection PyUnusedLocal
    def get_object(self, *args, **kwargs):
        return self.request.user


class LoginView(views.LoginView):
    redirect_authenticated_user = True
    template_name = "accounts/signin.html"
    authentication_form = AuthenticationForm


class LogoutView(views.LogoutView):
    next_page = "/"


class PasswordResetView(FormView):
    template_name = "accounts/reset.html"
    success_url = reverse_lazy("qs_accounts:signin")

    def get_form_class(self):
        return get_object_from_configuration("QS_PASSWORD_RESET_FORM")

    def form_valid(self, form):
        form.save(self.request)
        messages.success(self.request, _("We've e-mailed you instructions for setting a new password to the "
                                         "e-mail address you've submitted."))
        return super().form_valid(form)


class PasswordResetConfirmView(FormView):
    template_name = "accounts/reset-confirm.html"
    success_url = reverse_lazy("qs_accounts:signin")

    # noinspection PyMethodOverriding
    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, request, reset_token, *args, **kwargs):
        try:
            self.get_username()
        except SignatureExpired:
            messages.error(request, _("Password reset token expired."))
            return redirect(self.get_success_url())
        except BadSignature:
            messages.error(request, _("Invalid password reset token."))
            return redirect(self.get_success_url())
        return super().dispatch(request, reset_token, *args, **kwargs)

    def get_username(self):
        reset_token = self.kwargs["reset_token"]
        signer = TimestampSigner()
        expiration = get_configuration("PASSWORD_RESET_TIMEOUT")
        return signer.unsign(reset_token, max_age=expiration)

    def get_user(self):
        user_model = get_user_model()

        try:
            user = user_model.objects.get_by_natural_key(self.get_username())
        except user_model.DoesNotExist:
            return

        return user

    def get_form_class(self):
        return get_object_from_configuration("QS_PASSWORD_RESET_CONFIRM_FORM")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        if 'user' in kwargs:
            return kwargs

        kwargs['user'] = self.get_user()
        return kwargs

    def form_valid(self, form):
        form.save(self.request)
        messages.success(self.request, _("Password has been reset successfully."))
        return super().form_valid(form)


class SignupView(FormView):
    template_name = "accounts/signup.html"
    disallowed_url = reverse_lazy("qs_accounts:signup_closed")
    success_url = reverse_lazy("qs_accounts:signup_complete")

    def dispatch(self, request, *args, **kwargs):
        allowed = get_configuration("QS_SIGNUP_OPEN")
        if not allowed:
            return redirect(self.disallowed_url)
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        return get_object_from_configuration("QS_SIGNUP_FORM")

    def form_valid(self, form):
        form.save(request=self.request)
        messages.success(self.request, _("We've e-mailed you instructions for setting a new password to the "
                                         "e-mail address you've submitted."))

        return super().form_valid(form)


class SignupActivationView(TemplateView):
    template_name = 'accounts/activation-error.html'

    def get_success_url(self):
        return get_configuration("LOGIN_REDIRECT_URL")

    # noinspection PyMethodOverriding
    def get(self, request, activation_key, *args, **kwargs):
        signer = TimestampSigner()
        expiration = get_configuration("QS_SIGNUP_TOKEN_EXPIRATION")
        try:
            username = signer.unsign(activation_key, max_age=expiration)
        except (BadSignature, SignatureExpired):
            return super().get(request, *args, **kwargs)

        user_model = get_user_model()
        try:
            user = user_model.objects.activate(username)
        except user_model.DoesNotExist:
            return super().get(request, *args, **kwargs)

        if user.is_active:
            user_activated.send(sender=self.__class__, user=user, request=request)

        if get_configuration("QS_SIGNUP_AUTO_LOGIN"):
            self._login_user(request, user)
        return redirect(self.get_success_url())

    def _login_user(self, request, user):
        backend = get_backends()[0]  # Hack to bypass `authenticate()`.
        user.backend = "%s.%s" % (backend.__module__, backend.__class__.__name__)
        user_login(request, user)
        request.session['QS_SIGNUP_AUTO_LOGIN'] = True
        request.session.modified = True


class UserProfileView(LoginRequiredMixin, ProfileMixin, UpdateView):
    success_url = reverse_lazy('qs_accounts:profile')
    form_class = import_string(get_configuration("QS_PROFILE_FORM"))
    template_name = 'accounts/profile.html'

    def form_valid(self, form):
        messages.success(self.request, _(u'Succesfully updated profile.'))
        return super().form_valid(form)


class PasswordChangeView(LoginRequiredMixin, ProfileMixin, UpdateView):
    success_url = reverse_lazy('qs_accounts:profile')
    form_class = get_object_from_configuration("QS_PASSWORD_CHANGE_FORM")
    template_name = 'accounts/password-change.html'

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, _(u'Succesfully updated your password.'))
        return super().form_valid(form)


class EmailChangeView(LoginRequiredMixin, ProfileMixin, UpdateView):
    success_url = reverse_lazy('qs_accounts:profile')
    form_class = get_object_from_configuration("QS_EMAIL_CHANGE_FORM")
    template_name = 'accounts/email-change.html'

    def form_valid(self, form):
        messages.success(self.request, _(u"You'll receive an message in your new e-mail to check it."))
        return super().form_valid(form)


class EmailChangeConfirmationView(LoginRequiredMixin, ProfileMixin, RedirectView):
    url = reverse_lazy("qs_accounts:profile")

    # noinspection PyMethodOverriding
    def get(self, request, activation_key, *args, **kwargs):
        signer = Signer()
        try:
            username = signer.unsign(activation_key)
        except BadSignature:
            messages.error(self.request, _(u"Invalid e-mail configuration token."))
            return super().get(request, *args, **kwargs)

        user_model = get_user_model()
        try:
            user_model.objects.confirm_new_email(username)
            messages.success(self.request, _(u"New e-mail has been successfully configured."))
        except user_model.DoesNotExist:
            messages.error(self.request, _(u"E-mail not found."))

        return super().get(request, *args, **kwargs)

quickstartup/qs_accounts/templates/_accounts/accounts.html
{% extends "page.html" %}


{% block meta_tags %}{{ block.super }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block body_class %}accounts{% endblock %}


{% block container %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <div class="flash-messages">
                    {% include "_includes/message-panels.html" %}
                </div>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col-6">
                <div class="panel">
                    <div class="page-header">
                        <h1>{% block title %}{% endblock %}</h1>
                    </div>
                    {% block panel %}{% endblock %}
                </div>
            </div>
            <div class="col"></div>

        </div>
    </div>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/activation-error.html
{% extends "page.html" %}{% load i18n l10n %}


{% block meta_tags %}{{ block.super }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block body_class %}activation-error{% endblock %}


{% block menu_signup %}
    <a class="nav-item nav-link active" href="{% url "qs_accounts:signup" %}">{% trans "Sign up" %}</a>{% endblock %}


{% block container %}
    <div class="container-fluid">
        <div class="row flex-items-xs-center">
            <div class="col-xs-6">
                <div class="message panel">
                    <div class="page-header">
                        <h1>{% trans "Account activation failed" %}</h1>
                        <p>{% trans "Your account is already activated or your activation link is incorrect." %}</p>
                    </div>
                    <a class="btn btn-primary btn-lg btn-block" href="{% url "qs_accounts:signin" %}">
                        {% trans "Back to Sign in" %}
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/base-profile.html
{% extends "app.html" %}{% load i18n %}

{% block menu_profile_class %}active{% endblock %}

quickstartup/qs_accounts/templates/_accounts/email-change.html
{% extends "accounts/base-profile.html" %}{% load i18n l10n pages widget_tweaks %}

{% block content %}
    <h1>{% trans "Change E-Mail" %}</h1>

    <form action="" method="post" role="form">
        {% csrf_token %}

        <div class="row">
            {% include "_includes/form-errors.html" %}
        </div>

        <div class="row">
            <div class="form-group col-lg-8">
                <label class="form-control-label" for="id_email">{% trans "E-mail" %}</label>
                <input id="id_email" class="form-control form-control-lg" readonly value="{{ object.email }}">
            </div>
        </div>

        <div class="row">
            {% include "_includes/vertical-labeled-big-field.html" with field=form.new_email|attr:"autofocus" cols=8 %}
        </div>

        <div class="form-button-panel">
            <button class="btn btn-primary" type="submit">{% trans "Update" %}</button>
            <a href="{% url "qs_accounts:profile" %}" class="btn btn-link" role="button">{% trans "Cancel" %}</a>
        </div>
    </form>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/password-change.html
{% extends "accounts/base-profile.html" %}{% load i18n l10n pages widget_tweaks %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form action="." method="post" role="form">
        {% csrf_token %}

        {% include "_includes/form-errors.html" %}

        <div class="row">
            {% include "_includes/vertical-labeled-big-field.html" with field=form.old_password|attr:"autofocus" cols=6 %}
        </div>
        <div class="row">
            {% include "_includes/vertical-labeled-big-field.html" with field=form.new_password1 cols=6 %}
        </div>
        <div class="row">
            {% include "_includes/vertical-labeled-big-field.html" with field=form.new_password2 cols=6 %}
        </div>

        <div class="form-button-panel">
            <button class="btn btn-primary" type="submit">{% trans "Update" %}</button>
            <a href="{% url "qs_accounts:profile" %}" class="btn btn-link" role="button">{% trans "Cancel" %}</a>
        </div>
    </form>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/profile.html
{% extends "accounts/base-profile.html" %}{% load i18n l10n pages widget_tweaks %}

{% block content %}
    <h1>
        {% trans "Profile" %}
        <div class="btn-group btn-group-sm float-right" role="group">
            <a href="{% url "qs_accounts:email_change" %}" class="btn btn-sm btn-outline-primary" role="button">
                {% trans "Change E-Mail" %}
            </a>
            <a href="{% url "qs_accounts:password_change" %}" class="btn btn-sm btn-outline-primary" role="button">
                {% trans "Change Password" %}
            </a>
        </div>
    </h1>

    <form action="" method="post" role="form">
        {% csrf_token %}

        <div class="row">
            {% include "_includes/form-errors.html" %}
        </div>

        <div class="row">
            {% include "_includes/vertical-labeled-big-field.html" with field=form.name|attr:"autofocus" cols=6 %}
        </div>

        <div class="form-button-panel">
            <button class="btn btn-primary" type="submit">{% trans "Update" %}</button>
            <a href="javascript:history.back()" class="btn btn-link" role="button">{% trans "Cancel" %}</a>
        </div>
    </form>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/reset-confirm.html
{% extends "accounts/accounts.html" %}{% load i18n l10n pages widget_tweaks %}


{% block menu_signin %}
    <li class="nav-item active"><a class="nav-link" href="{% url "qs_accounts:signin" %}">{% trans "Sign in" %}</a>
    </li>{% endblock %}


{% block body_class %}{{ block.super }} reset-confirm{% endblock %}


{% block page_title %}{% trans "New password" %} — {{ block.super }}{% endblock %}
{% block title %}{% trans "New password" %}{% endblock %}


{% block panel %}
    {% block reset_confirm_form %}
        <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

        <form action="" method="post" role="form">
            {% csrf_token %}

            {% include "_includes/form-errors.html" %}

            {% block reset_confirm_form_fields %}
                {% include "_includes/vertical-placeholder-big-password.html" with field=form.new_password1|attr:"autofocus" %}
                {% include "_includes/vertical-placeholder-big-password.html" with field=form.new_password2 %}
            {% endblock %}

            <div class="form-group">
                <button class="btn btn-primary btn-lg btn-block" type="submit">
                    {% trans "Change password" %}
                </button>
            </div>
        </form>
    {% endblock %}
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/reset.html
{% extends "accounts/accounts.html" %}{% load i18n l10n pages widget_tweaks %}


{% block menu_signin %}
    <li class="nav-item active"><a class="nav-link" href="{% url "qs_accounts:signin" %}">{% trans "Sign in" %}</a>
    </li>{% endblock %}


{% block body_class %}{{ block.super }} reset{% endblock %}
{% block page_title %}{% trans "Reset password" %} — {{ block.super }}{% endblock %}
{% block title %}{% trans "Reset password" %}{% endblock %}


{% block panel %}
    {% block reset_form %}
        <p>{% trans "Enter your e-mail address below, and we'll send you instructions for setting a new one." %}</p>

        <form action="" method="post" role="form">
            {% csrf_token %}

            {% include "_includes/form-errors.html" %}

            {% block reset_fields %}
                {% include "_includes/vertical-placeholder-big-field.html" with field=form.email|attr:"autofocus" %}
            {% endblock %}

            <div class="form-group">
                <button class="btn btn-primary btn-lg btn-block" type="submit">{% trans "Reset" %}</button>
            </div>
        </form>
    {% endblock %}
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/signin.html
{% extends "accounts/accounts.html" %}{% load i18n l10n widget_tweaks %}


{% block menu_signin %}
    <li class="nav-item active"><a class="nav-link" href="{% url "qs_accounts:signin" %}">{% trans "Sign in" %}</a>
    </li>{% endblock %}

{% block body_class %}{{ block.super }} signup{% endblock %}
{% block title %}{% trans "Sign in" %}{% endblock %}
{% block page_title %}{% trans "Sign in" %} — {{ block.super }}{% endblock %}


{% block panel %}
    {% block signin_form %}
        <form action="" method="post" role="form">
            {% csrf_token %}

            {% include "_includes/form-errors.html" %}

            {% block signin_fields %}
                {% include "_includes/vertical-placeholder-big-field.html" with field=form.username|attr:"autofocus" %}
                {% include "_includes/vertical-placeholder-big-password.html" with field=form.password %}
            {% endblock %}

            <div class="form-group">
                <a href="{% url "qs_accounts:password_reset" %}">{% trans "Forgot password?" %}</a>
            </div>

            <div class="form-group">
                <button class="btn btn-primary btn-lg btn-block" type="submit">
                    {% trans "Sign in" %}
                </button>
            </div>

            <div class="form-group">
                {% trans "Don't have an account?" %}
                <a href="{% url "qs_accounts:signup" %}">{% trans "Sign up" %}.</a>
            </div>
        </form>
    {% endblock %}
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/signup-closed.html
{% extends "page.html" %}{% load i18n l10n %}


{% block meta_tags %}{{ block.super }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block body_class %}activation-error{% endblock %}


{% block menu_signup %}
    <li class="nav-item active"><a class="nav-link" href="{% url "qs_accounts:signup" %}">{% trans "Sign up" %}</a>
    </li>{% endblock %}


{% block container %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <div class="message panel">
                    <h1>{% trans "Signup is closed" %}</h1>
                    <p>
                        {% blocktrans %}This site is currently in closed beta.
                            If you want to be a beta tester of this service please contact us by contact
                            form.{% endblocktrans %}
                    </p>
                    <a class="btn btn-primary btn-lg btn-block" href="{% url "qs_contacts:contact" %}">
                        {% trans "Go to Contact" %}
                    </a>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/signup-complete.html
{% extends "page.html" %}{% load i18n l10n %}


{% block meta_tags %}{{ block.super }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block body_class %}signup-complete{% endblock %}


{% block menu_signup %}
    <li class="nav-item active"><a class="nav-link" href="{% url "qs_accounts:signup" %}">{% trans "Sign up" %}</a>
    </li>{% endblock %}

{% block container %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <div class="message panel">
                    <div class="page-header">
                        <h1>{% trans "Activation e-mail sent" %}</h1>
                        <p>{% trans "Please check your e-mail to complete the registration process." %}</p>
                    </div>
                    <a class="btn btn-primary btn-lg btn-block" href="{% url "qs_accounts:signin" %}">
                        {% trans "Back to Sign in" %}
                    </a>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

quickstartup/qs_accounts/templates/_accounts/signup.html
{% extends "accounts/accounts.html" %}{% load i18n l10n widget_tweaks %}


{% block menu_signup %}
    <li class="nav-item active"><a class="nav-link" href="{% url "qs_accounts:signup" %}">{% trans "Sign up" %}</a>
    </li>{% endblock %}

{% block body_class %}{{ block.super }} signup{% endblock %}
{% block title %}{% trans "Sign up" %}{% endblock %}
{% block page_title %}{% trans "Sign up" %} — {{ block.super }}{% endblock %}


{% block panel %}
    {% block signup_form %}
        <form action="" method="post" role="form">
            {% csrf_token %}

            {% include "_includes/form-errors.html" %}
            {% include "_includes/antispam.html" %}

            {% block signup_fields %}
                {% include "_includes/vertical-placeholder-big-field.html" with field=form.name|attr:"autofocus" %}
                {% include "_includes/vertical-placeholder-big-field.html" with field=form.email %}
                {% include "_includes/vertical-placeholder-big-password.html" with field=form.password1 %}
                {% include "_includes/vertical-placeholder-big-password.html" with field=form.password2 %}
            {% endblock %}

            <div class="form-group">
                <button class="btn btn-primary btn-lg btn-block" type="submit">
                    {% trans "Sign up" %}
                </button>
            </div>
        </form>
    {% endblock %}
{% endblock %}