quickstartup/qs_accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "qs_accounts"

urlpatterns = [
    # Auth
    path("signin/", views.LoginView.as_view(), name="signin"),
    path("signout/", views.LogoutView.as_view(), name="signout"),

    # Password reset
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<reset_token>/", views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),

    # Basic Registration
    path("signup/", view=views.SignupView.as_view(), name="signup"),
    path('signup/complete/', view=TemplateView.as_view(template_name='accounts/signup-complete.html', ),
         name='signup_complete'),
    path('activate/<activation_key>/', view=views.SignupActivationView.as_view(), name='activate'),
    path('signup/closed/', TemplateView.as_view(template_name='accounts/signup-closed.html'),
         name='signup_closed'),

    # Profile
    path("profile/", view=views.UserProfileView.as_view(), name="profile"),
    path("profile/password/", views.PasswordChangeView.as_view(), name="password_change"),
    path("profile/email/", views.EmailChangeView.as_view(), name="email_change"),
    path("profile/email/<activation_key>/", views.EmailChangeConfirmationView.as_view(),
         name="email_change_confirmation"),
]

testproject/testapp/urls.py
from django.urls import path

from .views import index


app_name = "app"


urlpatterns = [
    path("", index, name="index"),
]

testproject/urls.py
from django.urls import include, path

urlpatterns = [
    path("app/", include("testproject.testapp.urls")),
    path("", include("quickstartup.urls")),
]

quickstartup/core/templates/apps.html
{# Here we define the sctructure used by the application #}
{% extends "project.html" %}{% load i18n l10n pages widget_tweaks %}


{% block styles %}{{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}app/base.css">
{% endblock %}


{% block body_tag %}<body class="app">{% endblock %}


{% block navbar_menu %}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        {% block navbar_options %}{% endblock %}
    </ul>

    <ul class="nav navbar-nav navbar-right">
        {% block navbar_right_options %}{% endblock %}
        {% block menu_profile %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ user.email }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    {% block menu_profile_options %}
                    <li><a href="{% url "qs_accounts:profile" %}">{% trans "Profile" %}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url "qs_accounts:signout" %}">{% trans "Sign out" %}</a></li>
                    {% endblock %}
                </ul>
            </li>
        {% endblock %}
    </ul>
</div>
{% endblock %}


{% block container %}
<div class="container">

    {% include "_includes/message_panels.html" %}

    <div class="row">
        <div class="col-md-3">
            {% block sidebar %}
            <div class="sidebar-nav list-group">
                {% block sidebar_home %}<a class="list-group-item" href="{% url "app:index" %}">{% trans "Home" %}</a>{% endblock %}
            </div>
            {% endblock %}
        </div>

        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

quickstartup/core/templates/base.html
{# These base includes bootstrap & jquery used by Quickstartup. #}
{# If you have plans to use other CSS & JS frameworks you can change it here. #}
{% extends "html5.html" %}{% load i18n %}{% load l10n %}{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static "lib/bootstrap/css/bootstrap.css" %}">
{% endblock %}

{% block end_head %}
    <!--[if lt IE 9]>
      <script src="{% static "lib/respond/respond.min.js" %}"></script>
    <![endif]-->
{% endblock %}

{% block end_body %}
    <script src="{% static "lib/jquery/jquery.js" %}"></script>
    <script src="{% static "lib/bootstrap/js/bootstrap.js" %}"></script>
{% endblock %}