quickstartup/qs_accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "qs_accounts"

urlpatterns = [
    # Auth
    path("signin/", views.LoginView.as_view(), name="signin"),
    path("signout/", views.LogoutView.as_view(), name="signout"),

    # Password reset
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<reset_token>/", views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),

    # Basic Registration
    path("signup/", view=views.SignupView.as_view(), name="signup"),
    path('signup/complete/', view=TemplateView.as_view(template_name='accounts/signup-complete.html', ),
         name='signup_complete'),
    path('activate/<activation_key>/', view=views.SignupActivationView.as_view(), name='activate'),
    path('signup/closed/', TemplateView.as_view(template_name='accounts/signup-closed.html'),
         name='signup_closed'),

    # Profile
    path("profile/", view=views.UserProfileView.as_view(), name="profile"),
    path("profile/password/", views.PasswordChangeView.as_view(), name="password_change"),
    path("profile/email/", views.EmailChangeView.as_view(), name="email_change"),
    path("profile/email/<activation_key>/", views.EmailChangeConfirmationView.as_view(),
         name="email_change_confirmation"),
]

quickstartup/qs_pages/urls.py
from django.urls import path

from . import views

app_name = "qs_pages"

urlpatterns = [
    path("", views.index, name="index"),
]

testproject/urls.py
from django.urls import include, path

urlpatterns = [
    path("app/", include("testproject.testapp.urls")),
    path("", include("quickstartup.urls")),
]

quickstartup/qs_pages/models.py
from django.db import models
from django.template import loader
from django.utils.translation import gettext_lazy as _


class Page(models.Model):
    slug = models.SlugField(max_length=255, blank=True, unique=True, db_index=True,
                            help_text=_("URL Path. Example: about for /about/"))
    template_name = models.CharField(max_length=255, help_text=_("Template filename. Example: website/about.html"))
    login_required = models.BooleanField(default=False)

    @property
    def path(self):
        return "/{}/".format(self.slug) if self.slug else "/"

    def __str__(self):
        return self.path

    def __repr__(self):
        return "<Page: {}>".format(self.path)

    def get_absolute_url(self):
        return self.path

    @property
    def template(self):
        return loader.get_template(self.template_name)

quickstartup/qs_pages/forms.py
from django import forms

from .models import Page


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ("slug", "template_name", "login_required")

quickstartup/qs_pages/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Page


def website_page(request, path):
    slug = path.strip("/")
    page = get_object_or_404(Page, slug=slug)
    context = {"page": page, "slug": slug, "path": path}
    return HttpResponse(page.template.render(context, request))


def index(request):
    return render(request, "website/landing.html")

quickstartup/qs_pages/templates/_website/content.html
{% extends "page.html" %}{% load i18n l10n %}


{% block body_class %}{{ page.slug }}{% endblock %}


{% block container %}
    <div class="container-fluid">
        <div class="row flex-items-xs-center">
            <div class="col-xs-9">
                <nav class="breadcrumb">
                    <a class="breadcrumb-item" href="{% url "qs_pages:index" %}">{% trans "Home" %}</a>
                    <a class="breadcrumb-item active">{% block title %}{% endblock %}</a>
                </nav>
            </div>
            <div class="col-xs-9">
                <div class="content">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

quickstartup/qs_pages/templates/_website/landing.html
{% extends "page.html" %}{% load i18n l10n %}


{% block body_class %}landing{% endblock %}


{% block container %}
    <div class="container">
        <div class="jumbotron">
            <h1>{{ PROJECT_NAME }}</h1>
            <p>{% blocktrans %}Create your SaaS company quickly.{% endblocktrans %}</p>
            <p><a href="{% url "qs_accounts:signup" %}"
                  class="btn btn-success btn-lg">{% trans "Create your Account!" %}</a></p>
        </div>
    </div>

    <div class="container tour">
        <div class="row">
            <div class="col box">
                <h2>{% trans "Start Now!" %}</h2>
                <p>
{% blocktrans %}Quickstartup provides the building blocks to start your application development instantly.{% endblocktrans %}
                </p>
            </div>

            <div class="col box">
                <h2>{% trans "Go Live!" %}</h2>
                <p>
                    {% blocktrans %}Put your application in the air with a few simple steps.{% endblocktrans %}
                </p>
            </div>
        </div> <!-- row -->

        <div class="row">
            <div class="col box">
                <h2>{% trans "Focus on your business" %}</h2>
                <p>
{% blocktrans %}SaaS applications need many side features that deviate developers from the core
business. Quickstartup provides these features and allows you to keep focused on main
application development.{% endblocktrans %}
                </p>
            </div>

            <div class="col box">
                <h2>{% trans "Free and Open Source" %}</h2>
                <p>
{% blocktrans %}This project is Open Source and allows any entrepreneur starts their own SaaS
application business.{% endblocktrans %}
                </p>
            </div>
        </div>  <!-- row -->
    </div> <!-- .tour -->
{% endblock %}

quickstartup/qs_pages/templates/_website/privacy.html
{% extends "website/content.html" %}{% load i18n l10n %}


{% block meta_tags %}{{ block.super }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block page_title %}{% trans "Privacy Policy" %} — {{ block.super }}{% endblock page_title %}


{% block content %}
    <div class="page-header">
        <h1>{% block title %}{% trans "Privacy Policy" %}{% endblock %}</h1>
    </div>
    {% block privacy %}
        <p><a href="https://termsfeed.com/">{% trans "Create your Privacy Policy here" %}</a></p>
    {% endblock %}
{% endblock %}

quickstartup/qs_pages/templates/_website/terms.html
{% extends "website/content.html" %}{% load i18n l10n %}


{% block meta_tags %}{{ block.super }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block page_title %}{% trans "Terms of Service" %} — {{ block.super }}{% endblock page_title %}


{% block content %}
    <div class="page-header">
        <h1>{% block title %}{% trans "Terms of Service" %}{% endblock %}</h1>
    </div>
    {% block terms %}
        <p><a href="https://termsfeed.com/">{% trans "Create your Terms of Service here" %}</a></p>
    {% endblock %}
{% endblock %}